### ISSUE TITLE
Javascript error after package updates

### ISSUE THREAD

**Issue by Brutify** [Xzandro/sw-exporter#143]
Still getting this error after dungeon runs. I noticed this only happens when I have "run logger" enabled. This is using the v0.0.22 release last updated on May 16, 2018.
 
![image](https://user-images.githubusercontent.com/39577279/40462441-e3ab167a-5ec4-11e8-8fe5-90278b8933f7.png)

**Comment by Xzandro** [comment]
Can you be more specific? Which dungeon? Which monster involved? Can you even tell the exact data from the request & response event? You would need to activate the full-logger for that. This doesnt seem like a general problem, we had much more reports like that so please be as specific as possible.

**Comment by Brutify** [comment]
So far, it's happening in all the rune dungeons when "run logger" is enabled (Giant, Dragon, Necro). I will have more information later today, including request/response data.

**Comment by Xzandro** [comment]
Alright. I plan to release a new version soon so it might be good information. Otherwise I cant reproduce this.

**Comment by Xzandro** [comment]
I didn't look into the files too much, but is it possible that you use one of the new monsters in these runs? If yes. The new version I just released should fix this.

**Comment by Brutify** [comment]
Unfortunately, I'm still getting the same error with the RunLogger enabled. I am not using the new monsters in the runs.

**Comment by Xzandro** [comment]
Alright. Then I (or any other who wants to) need to have closer look at this when I have the time. :)
