### ISSUE TITLE
A Java script error occured in the proccess

### ISSUE THREAD

**Issue by ArvillB** [Xzandro/sw-exporter#165]
I tried reinstalling , changing ports and IP address and updating to latest java. No idea what's causing this error.

![image](https://user-images.githubusercontent.com/42757493/44695042-ff235500-aa3e-11e8-9c33-166706f093e1.png)

**Comment by Xzandro** [comment]
Normally this error should be fixed in the new versions. Are you sure you use it? Also, you don't need Java at all. This is written in JavaScript, huge difference.

**Comment by ArvillB** [comment]
yes. I had this error in version 22 and updated to 23 and still have the same problem. Deleted all saved logs/files thinking something was corrupted but same issue.

**Comment by gng4life** [comment]
Same issue here, anyone have any idea?

**Comment by gng4life** [comment]
I just upgraded to v24 and still this issue is there. Please help

**Comment by gng4life** [comment]
Would you give me specs/versions/etc and let me see if I can match your system. I have another system I will install it on today also. Thanks

**Comment by Psifour** [comment]
Currently there is no error handling being done in the error event that is passed to SWProxy.js
https://github.com/Xzandro/sw-exporter/blob/6581b2c9d43a278fb88a7e11a7996e097a293ad6/app/proxy/SWProxy.js#L64-L70 

Instead of checking the error that was passed it attempts to write HTTP status-code 500. Judging by what he has said there is some form of error that is being thrown AFTER the packet is sent and attempting to write the header causes an error message.

My suggested solution is to make the error message more robust and avoid sending a 500 unless we can verify that the response hasn't already been passed along.

**Comment by erossiiv** [comment]
I found out that I had a firewall (Tinywall) that was causing the SWExporter to not reach the server to install this.  Once I paused the firewall, I was able to use this.

**Comment by Xzandro** [comment]
This is an old error and SWEX got several updates over the years so I'm closing this for now and if anyone encounters such an error, feel free to create a new issue.
